

services:
    www:
        build: .
        ports:
            - "91:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports:
            - "3307:3306"
        restart: always
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: root
            MYSQL_PASSWORD: '1112marci-O'
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default

volumes:
    persistent:

