

services:
    www:
        build: .
        ports:
            - "91:80"
        volumes:
            - ./www:/var/www/html/www/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: root
            MYSQL_PASSWORD: 1112marci-O
            MYSQL_ROOT_PASSWORD: 1112marci-O
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 1112marci-O
            MYSQL_ROOT_PASSWORD: 1112marci-O
volumes:
    persistent:

